### PR TITLE
Clear French issues

### PR DESCRIPTION
**Pull request by aclerbois**
- Clear french sentence
- Change the commands by the right commands order and words

### CODE REVIEW

**Comment by v-radelg** [comment]
Hi @aclerbois , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by aclerbois** [comment]
@v-radelg I don't follow you, is the discussion about my Pull Request or about NuGet documentation in general?

**Comment by v-radelg** [comment]
Hi @aclerbois , your suggestions are being reviewed by our French linguistic moderator. Once he finish the review we will let you know the result.

Thanks for your support,

Microsoft C&E Localization Team

**Comment by gosali** [comment]
@aclerbois , Thank you for your feedback and suggestion! 
  
The suggestion will be merged to the production, we will re-release this articles in the next loc release round. 
  
Microsoft C&E Localization Team

**Pull request merged**
